services:
  df.userservice.api:
    image: ${USER_SERVICE_IMAGE:-df.userservice.api:latest}
    pull_policy: never
    platform: ${PREBUILT_PLATFORM:-linux/arm64}

  df.menuservice.api:
    image: ${MENU_SERVICE_IMAGE:-df.menuservice.api:latest}
    pull_policy: never
    platform: ${PREBUILT_PLATFORM:-linux/arm64}

  df.trackingservice.api:
    image: ${TRACKING_SERVICE_IMAGE:-df.trackingservice.api:latest}
    pull_policy: never
    platform: ${PREBUILT_PLATFORM:-linux/arm64}
