// <auto-generated />
using System;
using DF.OrderService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DF.OrderService.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DF.OrderService.Domain.Entities.FoodSplit.GroupCartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GroupSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MenuItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GroupSessionId");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("GroupCartItems", (string)null);
                });

            modelBuilder.Entity("DF.OrderService.Domain.Entities.FoodSplit.GroupOrderPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GroupSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentIntentId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GroupSessionId");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("PaymentIntentId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("GroupOrderPayments", (string)null);
                });

            modelBuilder.Entity("DF.OrderService.Domain.Entities.FoodSplit.GroupSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HostUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("HostUserId");

                    b.HasIndex("OrderId");

                    b.HasIndex("Status");

                    b.ToTable("GroupSessions", (string)null);
                });

            modelBuilder.Entity("DF.OrderService.Domain.Entities.FoodSplit.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GroupSessionId");

                    b.HasIndex("UserId");

                    b.HasIndex("GroupSessionId", "SessionToken")
                        .IsUnique();

                    b.HasIndex("GroupSessionId", "UserId");

                    b.ToTable("Participants", (string)null);
                });

            modelBuilder.Entity("DF.OrderService.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DeliverFromId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DeliverToId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DeliveredById")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("OrderedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Profit")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("DF.OrderService.Domain.Entities.OrderedDish", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DishId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderedDishes", (string)null);
                });

            modelBuilder.Entity("DF.OrderService.Domain.Entities.FoodSplit.GroupCartItem", b =>
                {
                    b.HasOne("DF.OrderService.Domain.Entities.FoodSplit.GroupSession", "GroupSession")
                        .WithMany("CartItems")
                        .HasForeignKey("GroupSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DF.OrderService.Domain.Entities.FoodSplit.Participant", "Participant")
                        .WithMany("CartItems")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupSession");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("DF.OrderService.Domain.Entities.FoodSplit.GroupOrderPayment", b =>
                {
                    b.HasOne("DF.OrderService.Domain.Entities.FoodSplit.GroupSession", "GroupSession")
                        .WithMany("Payments")
                        .HasForeignKey("GroupSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DF.OrderService.Domain.Entities.FoodSplit.Participant", "Participant")
                        .WithMany("Payments")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupSession");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("DF.OrderService.Domain.Entities.FoodSplit.GroupSession", b =>
                {
                    b.HasOne("DF.OrderService.Domain.Entities.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("DF.OrderService.Domain.Entities.FoodSplit.Participant", b =>
                {
                    b.HasOne("DF.OrderService.Domain.Entities.FoodSplit.GroupSession", "GroupSession")
                        .WithMany("Participants")
                        .HasForeignKey("GroupSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupSession");
                });

            modelBuilder.Entity("DF.OrderService.Domain.Entities.OrderedDish", b =>
                {
                    b.HasOne("DF.OrderService.Domain.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DF.OrderService.Domain.Entities.FoodSplit.GroupSession", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Participants");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("DF.OrderService.Domain.Entities.FoodSplit.Participant", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
